---
# Data Ingestion Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
  labels:
    app: data-ingestion
    tier: data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
        tier: data
    spec:
      containers:
      - name: data-ingestion
        image: tft-data-ingestion:latest
        ports:
        - containerPort: 8001
        env:
        - name: POLYGON_API_KEY
          valueFrom:
            secretKeyRef:
              name: tft-secrets
              key: polygon-api-key
        - name: REDDIT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: tft-secrets
              key: reddit-client-id
        - name: REDDIT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: tft-secrets
              key: reddit-client-secret
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: REDIS_URL
          value: "redis://redis:6379"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion
spec:
  selector:
    app: data-ingestion
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
  type: ClusterIP
---
# Sentiment Engine Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-engine
  labels:
    app: sentiment-engine
    tier: ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-engine
  template:
    metadata:
      labels:
        app: sentiment-engine
        tier: ml
    spec:
      nodeSelector:
        node-type: gpu-enabled
      containers:
      - name: sentiment-engine
        image: tft-sentiment-engine:latest
        ports:
        - containerPort: 8002
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: SENTIMENT_MODEL
          value: "cardiffnlp/twitter-roberta-base-sentiment-latest"
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-engine
spec:
  selector:
    app: sentiment-engine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8002
  type: ClusterIP
---
# TFT Predictor Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tft-predictor
  labels:
    app: tft-predictor
    tier: ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tft-predictor
  template:
    metadata:
      labels:
        app: tft-predictor
        tier: ml
    spec:
      nodeSelector:
        node-type: gpu-enabled
      containers:
      - name: tft-predictor
        image: tft-predictor:latest
        ports:
        - containerPort: 8003
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: tft-secrets
              key: postgres-url
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "8"
            memory: "32Gi"
            nvidia.com/gpu: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: tft-predictor
spec:
  selector:
    app: tft-predictor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8003
  type: ClusterIP
---
# Trading Engine Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-engine
  labels:
    app: trading-engine
    tier: trading
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trading-engine
  template:
    metadata:
      labels:
        app: trading-engine
        tier: trading
    spec:
      nodeSelector:
        node-type: low-latency
      containers:
      - name: trading-engine
        image: tft-trading-engine:latest
        ports:
        - containerPort: 8004
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: ALPACA_API_KEY
          valueFrom:
            secretKeyRef:
              name: tft-secrets
              key: alpaca-api-key
        - name: ALPACA_API_SECRET
          valueFrom:
            secretKeyRef:
              name: tft-secrets
              key: alpaca-api-secret
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: tft-secrets
              key: postgres-url
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: trading-engine
spec:
  selector:
    app: trading-engine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8004
  type: ClusterIP
---
# Orchestrator Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  labels:
    app: orchestrator
    tier: coordination
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
        tier: coordination
    spec:
      containers:
      - name: orchestrator
        image: tft-orchestrator:latest
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: DATA_INGESTION_URL
          value: "http://data-ingestion"
        - name: SENTIMENT_ENGINE_URL
          value: "http://sentiment-engine"
        - name: TFT_PREDICTOR_URL
          value: "http://tft-predictor"
        - name: TRADING_ENGINE_URL
          value: "http://trading-engine"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
# Horizontal Pod Autoscalers
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-ingestion-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-ingestion
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sentiment-engine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sentiment-engine
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trading-engine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trading-engine
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
